 Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

 Nominal/OHE Encoding

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [5]:
encoder=OneHotEncoder()

In [6]:
## perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [7]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [8]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [9]:
## for new data
encoder.transform([['blue']]).toarray()

e:\anaconda\envs\abdullah\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [10]:
pd.concat([df,encoder_df])

   color  color_blue  color_green  color_red
0    red         NaN          NaN        NaN
1   blue         NaN          NaN        NaN
2  green         NaN          NaN        NaN
3  green         NaN          NaN        NaN
4    red         NaN          NaN        NaN
5   blue         NaN          NaN        NaN
0    NaN         0.0          0.0        1.0
1    NaN         1.0          0.0        0.0
2    NaN         0.0          1.0        0.0
3    NaN         0.0          1.0        0.0
4    NaN         0.0          0.0        1.0
5    NaN         1.0          0.0        0.0